describe('Create needs Test',() => {
    it ('Create needs test',() => {
        cy.fixture('Total').then(data => {
        cy.log('Переxод на страницу авторизации')
        cy.visit(data.login_url)
        cy.log('Ввод несуществующего логина')
        cy.get('input[class="form-input--text form-input"]').type(data.login_Employer)
        cy.log('Ввод существующего пароля')
        cy.get('input[class="form-input--password form-input"]').type(data.password)
        cy.log('Клик по кнопке Войти')
        cy.get('div[class="login-form__button"] button[type="submit"]').click()
        cy.wait(1500)
        
        cy.log('Заходим в раздел Потребности')
        cy.get(':nth-child(6) > .menu-item__item-name').click()
        cy.log('Кликаем на создание потребности')
        cy.get('.needs-block__filters-wrapper > .button').click()
        cy.log('Прописываем должность')
        cy.get('.desktop-modal__content > .vacancy-need-wrapper > .form > :nth-child(1) > .form__labels > .labels > :nth-child(1) > .form-control--responsive > .form-input--text').type(data.job_name, { force: true })
        cy.log('Прописываем зарплату')
        cy.get('.desktop-modal__content > .vacancy-need-wrapper > .form > :nth-child(1) > .form__labels > .labels > :nth-child(2) > .salary-field > .salary-field__wrapper--bottom > .radio-list > :nth-child(2) > .radio-component__label').click()
        cy.log('Прописываем обязанности')
        cy.get('.desktop-modal__content > .vacancy-need-wrapper > .form > :nth-child(1) > .form__labels > .labels > :nth-child(3) > .form-control > .form-area').type(data.responsibilities)
        cy.log('Прописываем требования')
        cy.get('.desktop-modal__content > .vacancy-need-wrapper > .form > :nth-child(1) > .form__labels > .labels > :nth-child(4) > .form-control > .form-area').type(data.requirements)
        cy.log('Прописываем тип занятости работы')
        cy.get('.desktop-modal__content > .vacancy-need-wrapper > .form > :nth-child(1) > .form__labels > .labels > :nth-child(5) > .form-select > :nth-child(2) > .form-select__selected').click()
        cy.get('.form-select__items > :nth-child(1)').click()
        cy.log('Кликаем на кнопку создания потребности')
        cy.get('.desktop-modal__content > .vacancy-need-wrapper > .form > .form__buttons > .button').click({force:true})
        })
    })
})    